version: "3.9"

name: pharmacy-system

services:
  # ==========================
  # DATABASE
  # ==========================
  db:
    image: mysql:8.0
    container_name: pharmacy_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./Database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - pharmacy_network

  # ==========================
  # BACKEND (.NET API)
  # ==========================
  backend:
    image: ghcr.io/eduardohanacleto/pharmacy-backend:latest
    container_name: pharmacy_api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        server=db;
        port=3306;
        database=${MYSQL_DATABASE};
        user=${MYSQL_USER};
        password=${MYSQL_PASSWORD}
    ports:
      - "5000:80"
    networks:
      - pharmacy_network

  # ==========================
  # REDIS CACHE
  # ==========================
  redis:
    image: redis:7
    container_name: pharmacy_redis
    restart: always
    networks:
      - pharmacy_network

  # ==========================
  # FRONTEND (Vue + Nginx)
  # ==========================
  frontend:
    image: ghcr.io/eduardohanacleto/pharmacy-frontend:latest
    container_name: pharmacy_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - pharmacy_network

# ==========================
# VOLUMES
# ==========================
volumes:
  db_data:

# ==========================
# NETWORK
# ==========================
networks:
  pharmacy_network:
    driver: bridge
